### ISSUE TITLE
Fix CLang-Tidy Warnings

### ISSUE THREAD

**Issue by mt-xing** [onewordstudios/sweetspace#104]
Blocked by #99

Fix all warnings and then turn on merge enforcement
Wendy does `GameGraphRoot`
Xing does all else

EDIT: Aashna @asaxena5 can we get some help with `HealthNode`? Not sure how to clean that up.

**Comment by mt-xing** [comment]
I've finished my section as soon as #107 is merged. Passing this off to @wenjiazhang and @asaxena5

**Comment by asaxena5** [comment]
> I've finished my section as soon as #107 is merged. Passing this off to @wenjiazhang and @asaxena5

I've finished HealthNode, so all you @wenjiazhang !
