### ISSUE TITLE
Animation Node Crash

### ISSUE THREAD

**Issue by mt-xing** [onewordstudios/sweetspace#332]

**Comment by ssorenson130** [comment]
![image](https://user-images.githubusercontent.com/34524470/117586339-6ccb1e80-b0cc-11eb-9ae5-adbd954a0f16.png)

**Comment by mt-xing** [comment]
![image](https://user-images.githubusercontent.com/6147405/120910394-9edc8b80-c64c-11eb-8426-f8b07b2575c5.png)

![image](https://user-images.githubusercontent.com/6147405/120910399-a8fe8a00-c64c-11eb-824e-c19ff9b02e04.png)

![image](https://user-images.githubusercontent.com/6147405/120910401-abf97a80-c64c-11eb-9d61-d0431db0a980.png)
